context:
  version: "1.15.3"

package:
  name: js-beautify
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/js-beautify/-/js-beautify-${{ version }}.tgz
  sha256: 5e2680e72a241a040b9f21bfd755a794462a3c270e93320867dc0a896ed57817

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - css-beautify --help
      - html-beautify --help
      - js-beautify --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Beautifier for javascript
  homepage: https://beautifier.io/
  repository: https://github.com/beautifier/js-beautify

extra:
  recipe-maintainers:
    - danielnachun
